# docker-compose.yml

services:
  db:
    image: postgres:16
    env_file: .env
    ports:
      - "5431:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
      
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      ollama:
        condition: service_started
    working_dir: /app
    env_file: .env
    command:
      sh -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"

  worker:
    build:
      context: ./backend
    volumes:
      - ./backend:/app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
      ollama:
        condition: service_started
    command: celery -A tasks.celery_app worker --loglevel=info

  training:
    build: 
      context: ./training
    container_name: training
    profiles: ["training"]
    ports:
      - "8888:8888"
    volumes:
        - ./backend:/backend
        - ./training:/app
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/backend
      - MLFLOW_TRACKING_URI=http://experiment_tracking:5000
    depends_on:
      - experiment_tracking
    env_file:
      - .env
    command: start-notebook.sh --ServerApp.token='' --ServerApp.password=''
  
  experiment_tracking:
    image: ghcr.io/mlflow/mlflow:latest
    container_name: experiment_tracking
    profiles: ["training"]
    ports:
      - "5000:5000"
    volumes:
      - experiment_tracking_data:/root/data
    command: mlflow server --allowed-hosts "*" --backend-store-uri sqlite:////root/data/mlflow.db --port 5000 --host 0.0.0.0

volumes:
  postgres_data:
  ollama_data:
  experiment_tracking_data: