"""update_attachment_schema

Revision ID: 33c315f0f1b3
Revises: 3bf19eefc547
Create Date: 2026-02-16 05:25:14.639319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33c315f0f1b3'
down_revision: Union[str, None] = '3bf19eefc547'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('google_attachment_id', sa.String(), nullable=False))
    op.add_column('attachments', sa.Column('mime_type', sa.String(), nullable=True))
    op.add_column('attachments', sa.Column('size', sa.Integer(), nullable=True))
    op.alter_column('attachments', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_column('attachments', 'filetype')
    op.drop_column('attachments', 'url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attachments', sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('attachments', sa.Column('filetype', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('attachments', 'filename',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('attachments', 'size')
    op.drop_column('attachments', 'mime_type')
    op.drop_column('attachments', 'google_attachment_id')
    # ### end Alembic commands ###
