"""Added is_processed flag

Revision ID: 3bf19eefc547
Revises: e84375e47970
Create Date: 2026-02-11 23:26:38.192259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf19eefc547'
down_revision: Union[str, None] = 'e84375e47970'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('summary', sa.String(), nullable=True))
    op.add_column('emails', sa.Column('is_processed', sa.Boolean(), nullable=True))
    op.create_index(op.f('ix_emails_is_processed'), 'emails', ['is_processed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_emails_is_processed'), table_name='emails')
    op.drop_column('emails', 'is_processed')
    op.drop_column('emails', 'summary')
    # ### end Alembic commands ###
