"""remove is_spam column to emails

Revision ID: dc85107e59c3
Revises: cf342677972a
Create Date: 2026-02-25 00:07:34.897079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc85107e59c3'
down_revision: Union[str, None] = 'cf342677972a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('emails', 'is_spam')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emails', sa.Column('is_spam', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
