"""Removed followup table, will implement that in future

Revision ID: f5a435e8b575
Revises: 1fe6b5404997
Create Date: 2026-02-28 03:21:44.810936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f5a435e8b575'
down_revision: Union[str, None] = '1fe6b5404997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_followups_id'), table_name='followups')
    op.drop_table('followups')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followups',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('email_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('remind_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['email_id'], ['emails.id'], name=op.f('followups_email_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('followups_pkey'))
    )
    op.create_index(op.f('ix_followups_id'), 'followups', ['id'], unique=False)
    # ### end Alembic commands ###
